#pragma once

#ifdef ESP_PLATFORM
#include "sdkconfig.h"
#define WDC_SHELL_TARGET CONFIG_IDF_TARGET
#else
#define WDC_SHELL_TARGET "host"
#endif

#define WDC_SHELL_NAME        "wdc-" WDC_SHELL_TARGET "-shell"
#define WDC_SHELL_VERSION     "0.1.0-r9"
#define WDC_SHELL_BUILD_STAGE "R9"

#ifndef WDC_SHELL_BUILD_ID
#define WDC_SHELL_BUILD_ID WDC_SHELL_VERSION "-" WDC_SHELL_BUILD_STAGE
#endif

/* R9 keeps production non-effectful, enforces manifest runtime limits, and adds production security preflight/signature policy. */
/* R8.2 production boot: effectful GPIO/network self-tests disabled */
#ifndef WDC_BUILD_PROFILE_PROD
#define WDC_BUILD_PROFILE_PROD 1
#endif
#ifndef WDC_ENABLE_EFFECTFUL_SELF_TESTS
#define WDC_ENABLE_EFFECTFUL_SELF_TESTS 0
#endif
#ifndef WDC_ENABLE_BOOT_DIAGNOSTIC_PROBES
#define WDC_ENABLE_BOOT_DIAGNOSTIC_PROBES 0
#endif
#ifndef WDC_ENABLE_ACTIVE_SLOT_BOOT
#define WDC_ENABLE_ACTIVE_SLOT_BOOT 1
#endif
#define WDC_NO_BUNDLE_MODE 0
#define WDC_R4_STATIC_RUNTIME_SMOKE 0
#define WDC_R4_EVENT_RUNTIME_SMOKE  0
#define WDC_R5_STATIC_RUNTIME_SMOKE  0
#define WDC_R6_STATIC_RUNTIME_SMOKE  0
#define WDC_R6_BUNDLE_VERIFY_SMOKE   WDC_ENABLE_BOOT_DIAGNOSTIC_PROBES
#define WDC_R7_ACTIVATION_SMOKE      0
#define WDC_R8_ACTIVE_SLOT_SMOKE     WDC_ENABLE_ACTIVE_SLOT_BOOT
#define WDC_R8_NETWORK_SMOKE         WDC_ENABLE_EFFECTFUL_SELF_TESTS
#define WDC_R7_PROBATION_HEALTH_CHECKS 1u
#define WDC_R7_MAX_CANDIDATE_BOOTS     1u
#define WDC_R3_STATIC_RUNTIME_SMOKE WDC_R4_STATIC_RUNTIME_SMOKE

#define WDC_SHELL_TASK_NAME          "wdc_shell"
#define WDC_SHELL_TASK_STACK_BYTES   6144u
#define WDC_SHELL_TASK_PRIORITY      5u
#define WDC_NO_BUNDLE_IDLE_PERIOD_MS 10000u

#define WDC_R4_RUNTIME_STACK_BYTES  (16u * 1024u)
#define WDC_R4_RUNTIME_HEAP_BYTES   (64u * 1024u)
#define WDC_R4_EXEC_STACK_BYTES     (16u * 1024u)

#define WDC_R5_RUNTIME_STACK_BYTES  WDC_R4_RUNTIME_STACK_BYTES
#define WDC_R5_RUNTIME_HEAP_BYTES   WDC_R4_RUNTIME_HEAP_BYTES
#define WDC_R5_EXEC_STACK_BYTES     WDC_R4_EXEC_STACK_BYTES

#define WDC_R6_RUNTIME_STACK_BYTES  WDC_R5_RUNTIME_STACK_BYTES
#define WDC_R6_RUNTIME_HEAP_BYTES   WDC_R5_RUNTIME_HEAP_BYTES
#define WDC_R6_EXEC_STACK_BYTES     WDC_R5_EXEC_STACK_BYTES

#define WDC_R7_RUNTIME_STACK_BYTES  WDC_R6_RUNTIME_STACK_BYTES
#define WDC_R7_RUNTIME_HEAP_BYTES   WDC_R6_RUNTIME_HEAP_BYTES
#define WDC_R7_EXEC_STACK_BYTES     WDC_R6_EXEC_STACK_BYTES

#define WDC_R8_RUNTIME_STACK_BYTES  WDC_R7_RUNTIME_STACK_BYTES
#define WDC_R8_RUNTIME_HEAP_BYTES   WDC_R7_RUNTIME_HEAP_BYTES
#define WDC_R8_EXEC_STACK_BYTES     WDC_R7_EXEC_STACK_BYTES
#define WDC_R8_BUNDLE_BUFFER_BYTES  (256u * 1024u)
#define WDC_R8_2_RUNTIME_LIMITS_FROM_MANIFEST 1
#define WDC_R9_PRODUCTION_SIGNATURE_POLICY 1
#define WDC_R9_PRODUCTION_REJECTS_DEV_SIGNATURES 1
#define WDC_R9_REQUIRE_PRODUCTION_VERIFIER_CALLBACK 1
#define WDC_R9_PRODUCTION_SECURITY_PROFILE 1

#define WDC_R3_RUNTIME_STACK_BYTES  WDC_R4_RUNTIME_STACK_BYTES
#define WDC_R3_RUNTIME_HEAP_BYTES   WDC_R4_RUNTIME_HEAP_BYTES
#define WDC_R3_EXEC_STACK_BYTES     WDC_R4_EXEC_STACK_BYTES
